events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 9072;
        server_name 192.168.91.139;

        location / {
            root   E:/daping/;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /assets {
            alias E:/daping/assets;
            autoindex on;
        }
    }
}